
********************************************************************************************
Image failed at 2016-07-29 00:51:18
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2311, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:51:21
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:51:28
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:51:31
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:51:35
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:51:37
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:51:41
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:51:45
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0913.JPG'

********************************************************************************************
Image failed at 2016-07-29 00:51:47
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0916.JPG'

********************************************************************************************
Image failed at 2016-07-29 00:51:49
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0918.jpg'

********************************************************************************************
Image failed at 2016-07-29 00:51:51
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:51:54
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:51:58
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:52:02
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:52:05
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:52:08
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0937.jpg'

********************************************************************************************
Image failed at 2016-07-29 00:52:09
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:52:11
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 00:52:14
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0945.jpg'

********************************************************************************************
Image failed at 2016-07-29 00:52:16
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0947.jpg'

********************************************************************************************
Image failed at 2016-07-29 00:52:16
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 314, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0948.jpg'

********************************************************************************************
Image failed at 2016-07-29 10:54:32
ID: adb1be81-c9b4-4ca1-a681-711460080d76
ID: nam_ua395-6.1_170Traceback (most recent call last):
  File "flatArrangeCreate.py", line 325, in makeGallery
    if os.path.isfile(image):
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "C:\Python27\lib\shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 10:54:33
ID: adb1be81-c9b4-4ca1-a681-711460080d76
ID: nam_ua395-6.1_170Traceback (most recent call last):
  File "flatArrangeCreate.py", line 328, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "C:\Python27\lib\shutil.py", line 52, in copyfileobj
    fdst.write(buf)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 10:54:35
ID: adb1be81-c9b4-4ca1-a681-711460080d76
ID: nam_ua395-6.1_170Traceback (most recent call last):
  File "flatArrangeCreate.py", line 325, in makeGallery
    if os.path.isfile(image):
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "C:\Python27\lib\shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 10:54:36
ID: adb1be81-c9b4-4ca1-a681-711460080d76
ID: nam_ua395-6.1_170Traceback (most recent call last):
  File "flatArrangeCreate.py", line 331, in makeGallery
    imageCount = imageCount + 1
  File "C:\Python27\lib\subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "C:\Python27\lib\subprocess.py", line 1051, in _communicate
    stdout_thread.join()
  File "C:\Python27\lib\threading.py", line 949, in join
    self.__block.wait()
  File "C:\Python27\lib\threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 10:54:41
ID: adb1be81-c9b4-4ca1-a681-711460080d76
ID: nam_ua395-6.1_170Traceback (most recent call last):
  File "flatArrangeCreate.py", line 328, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "C:\Python27\lib\shutil.py", line 52, in copyfileobj
    fdst.write(buf)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 10:55:21
ID: adb1be81-c9b4-4ca1-a681-711460080d76
ID: nam_ua395-6.1_170Traceback (most recent call last):
  File "flatArrangeCreate.py", line 331, in makeGallery
    imageCount = imageCount + 1
  File "C:\Python27\lib\subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "C:\Python27\lib\subprocess.py", line 1051, in _communicate
    stdout_thread.join()
  File "C:\Python27\lib\threading.py", line 949, in join
    self.__block.wait()
  File "C:\Python27\lib\threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 10:55:21
ID: adb1be81-c9b4-4ca1-a681-711460080d76
ID: nam_ua395-6.1_170Traceback (most recent call last):
  File "flatArrangeCreate.py", line 328, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "C:\Python27\lib\shutil.py", line 52, in copyfileobj
    fdst.write(buf)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 10:55:22
ID: adb1be81-c9b4-4ca1-a681-711460080d76
ID: nam_ua395-6.1_170Traceback (most recent call last):
  File "flatArrangeCreate.py", line 325, in makeGallery
    if os.path.isfile(image):
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "C:\Python27\lib\shutil.py", line 52, in copyfileobj
    fdst.write(buf)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 10:55:22
ID: adb1be81-c9b4-4ca1-a681-711460080d76
ID: nam_ua395-6.1_170Traceback (most recent call last):
  File "flatArrangeCreate.py", line 325, in makeGallery
    if os.path.isfile(image):
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "C:\Python27\lib\shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 10:55:23
ID: adb1be81-c9b4-4ca1-a681-711460080d76
ID: nam_ua395-6.1_170Traceback (most recent call last):
  File "flatArrangeCreate.py", line 331, in makeGallery
    imageCount = imageCount + 1
  File "C:\Python27\lib\subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "C:\Python27\lib\subprocess.py", line 1051, in _communicate
    stdout_thread.join()
  File "C:\Python27\lib\threading.py", line 949, in join
    self.__block.wait()
  File "C:\Python27\lib\threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 10:55:24
ID: adb1be81-c9b4-4ca1-a681-711460080d76
ID: nam_ua395-6.1_170Traceback (most recent call last):
  File "flatArrangeCreate.py", line 325, in makeGallery
    if os.path.isfile(image):
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "C:\Python27\lib\shutil.py", line 52, in copyfileobj
    fdst.write(buf)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 10:55:24
ID: adb1be81-c9b4-4ca1-a681-711460080d76
ID: nam_ua395-6.1_170Traceback (most recent call last):
  File "flatArrangeCreate.py", line 325, in makeGallery
    if os.path.isfile(image):
  File "C:\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "C:\Python27\lib\shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 11:20:18
ID: 8209e17d-9d64-45b5-9b99-431d95cb6ab0
ID: nam_ua395-6.4.1_1Traceback (most recent call last):
  File "flatArrangeCreate.py", line 328, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 11:20:19
ID: 8209e17d-9d64-45b5-9b99-431d95cb6ab0
ID: nam_ua395-6.4.1_1Traceback (most recent call last):
  File "flatArrangeCreate.py", line 328, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 11:20:20
ID: 8209e17d-9d64-45b5-9b99-431d95cb6ab0
ID: nam_ua395-6.4.1_1Traceback (most recent call last):
  File "flatArrangeCreate.py", line 328, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 11:20:32
ID: 8209e17d-9d64-45b5-9b99-431d95cb6ab0
ID: nam_ua395-6.4.1_1Traceback (most recent call last):
  File "flatArrangeCreate.py", line 350, in makeGallery
    if child.tag == "file":
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 11:20:33
ID: 8209e17d-9d64-45b5-9b99-431d95cb6ab0
ID: nam_ua395-6.4.1_1Traceback (most recent call last):
  File "flatArrangeCreate.py", line 328, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 11:20:34
ID: 8209e17d-9d64-45b5-9b99-431d95cb6ab0
ID: nam_ua395-6.4.1_1Traceback (most recent call last):
  File "flatArrangeCreate.py", line 328, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\JpegImagePlugin.py", line 728, in jpeg_factory
    im = JpegImageFile(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\JpegImagePlugin.py", line 321, in _open
    handler(self, i)
  File "C:\Python27\lib\site-packages\PIL\JpegImagePlugin.py", line 66, in APP
    s = ImageFile._safe_read(self.fp, n)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 518, in _safe_read
    return fp.read(size)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 11:20:34
ID: 8209e17d-9d64-45b5-9b99-431d95cb6ab0
ID: nam_ua395-6.4.1_1Traceback (most recent call last):
  File "flatArrangeCreate.py", line 341, in makeGallery
    if not os.path.isfile(os.path.join(folderDip, newThumbnail)):
  File "C:\Python27\lib\genericpath.py", line 29, in isfile
    st = os.stat(path)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 11:20:35
ID: 8209e17d-9d64-45b5-9b99-431d95cb6ab0
ID: nam_ua395-6.4.1_1Traceback (most recent call last):
  File "flatArrangeCreate.py", line 328, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\JpegImagePlugin.py", line 728, in jpeg_factory
    im = JpegImageFile(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\JpegImagePlugin.py", line 321, in _open
    handler(self, i)
  File "C:\Python27\lib\site-packages\PIL\JpegImagePlugin.py", line 66, in APP
    s = ImageFile._safe_read(self.fp, n)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 518, in _safe_read
    return fp.read(size)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 11:28:14
ID: 2adf6c85-efd7-4fee-936f-c676c76b285f
ID: nam_ua395-6.1_3Traceback (most recent call last):
  File "flatArrangeCreate.py", line 328, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2280, in open
    fp = builtins.open(filename, "rb")
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 11:38:41
ID: 8209e17d-9d64-45b5-9b99-431d95cb6ab0
ID: nam_ua395-6.4.1_1Traceback (most recent call last):
  File "flatArrangeCreate.py", line 342, in makeGallery
    if not os.path.isfile(os.path.join(folderDip, newThumbnail)):
  File "C:\Python27\lib\genericpath.py", line 29, in isfile
    st = os.stat(path)
KeyboardInterrupt

********************************************************************************************
Image failed at 2016-07-29 12:28:07
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2311, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:07
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:07
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:07
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:07
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:08
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:08
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:08
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0913.JPG'

********************************************************************************************
Image failed at 2016-07-29 12:28:09
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0916.JPG'

********************************************************************************************
Image failed at 2016-07-29 12:28:09
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0918.jpg'

********************************************************************************************
Image failed at 2016-07-29 12:28:09
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:09
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:09
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:09
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:10
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:10
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0937.jpg'

********************************************************************************************
Image failed at 2016-07-29 12:28:10
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:10
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2307, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2297, in _open_core
    im = factory(fp, filename)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 264, in _open
    self.load()
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 267, in load
    im = self.ico.getimage(self.size)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 150, in getimage
    return self.frame(i)
  File "C:\Python27\lib\site-packages\PIL\IcoImagePlugin.py", line 169, in frame
    im = BmpImagePlugin.DibImageFile(self.buf)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 97, in __init__
    self._open()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 217, in _open
    self._bitmap()
  File "C:\Python27\lib\site-packages\PIL\BmpImagePlugin.py", line 123, in _bitmap
    raise IOError("Unsupported BMP header type (%d)" % file_info['header_size'])
IOError: Unsupported BMP header type (65536)

********************************************************************************************
Image failed at 2016-07-29 12:28:10
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0945.jpg'

********************************************************************************************
Image failed at 2016-07-29 12:28:10
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0947.jpg'

********************************************************************************************
Image failed at 2016-07-29 12:28:10
ID: a7fb15bb-def3-4ea0-935f-9d843ed3c1f3
ID: nam_ua395-8.1_4Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-rCZhWxDaxgZPZ9bZYXiWLe\\data\\dvd_batch3\\Jim_Acker\\IMG_0948.jpg'

********************************************************************************************
Image failed at 2016-07-29 15:34:43
ID: 3b35935c-4cd9-4950-b679-4a38cc7bb918
ID: nam_ua395-1.10_32Traceback (most recent call last):
  File "flatArrangeCreate.py", line 334, in makeGallery
    testImage = Image.open(image)
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2317, in open
    % (filename if filename else fp))
IOError: cannot identify image file '\\\\LINCOLN\\Masters\\Special Collections\\accessions\\SIP\\ua395-AZS3dUtnYyy8cMKo9fNYVi\\data\\dvd_batch1\\20003961\\DSC_0596.JPG'
